# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-24 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180524_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_time'], 'verbose_name': '博客', 'verbose_name_plural': '博客'},
        ),
    ]
