# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-24 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180524_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='article',
            name='digest',
            field=models.TextField(verbose_name='摘要'),
        ),
    ]
